<html>
<body>
報告對 <code>testing.T.FailNow</code> 和位於測試檔案 goroutine 中的類似方法的呼叫。
<p>像 <code>FailNow</code> 這種方法會呼叫 <code>runtime.Goexit</code>，並停止呼叫 goroutine，而不是測試。
  因此，必須僅從執行測試或基準的 goroutine 中呼叫。</p>
<p>有關 <code>FailNow</code> 的更多資訊，請參閱 <a href="https://pkg.go.dev/testing#T.FailNow">go.dev 上的 func (*T) FailNow</a>。</p>
<p>範例：</p>
<pre><code>func TestFoo(t *testing.T) {
  go func() {
    t.Fatal("oops") // 退出 goroutine，而不是 TestFoo
  }()
}</code></pre>
<p>在套用<b>取代為 'Error' 和 'return'</b> 快速修復後：</p>
<pre><code>func TestFoo(t *testing.T) {
  go func() {
    t.Error("oops")
    return
  }()
}</code>
</pre>
</body>
</html>